name: Check Relative Links
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Markdown link checker
        run: npm install -g markdown-link-check

      - name: Check links in Markdown files
        run: |
          find . -name "*.md" -print0 | xargs -0 markdown-link-check
